version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          name: Installing requirements
          command: |
            virtualenv virtualenv
            . virtualenv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "virtualenv"
      
      - run:
          name: Running unit tests
          command: |
            . virtualenv/bin/activate
            cd teamstars
            python manage.py raven test
            python manage.py test

      - store_artifacts:
          path: test-reports/
          destination: teamstars-test-reports
      - store_test_results:
          path: test-reports/

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/python:2.7.14-stretch-browsers
    steps:
      - checkout

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy teamstars-prod

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
