version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      
      - run:
          command: |
            . venv/bin/activate
            cd teamstars
            python manage.py raven test
            python manage.py test

      - store_artifacts:
          path: test-reports/
          destination: teamstars-test-reports
      - store_test_results:
          path: test-reports/